[[packages]]
name = "bazelbuild/rules_android_ndk"
sha256sum = "89bf5012567a5bade4c78eac5ac56c336695c3bfd281a9b0894ff6605328d2d5"
downloadLocation = "https://github.com/bazelbuild/rules_android_ndk/releases/download/v0.1.3/rules_android_ndk-v0.1.3.tar.gz"
license = "Apache-2.0"
version = "0.1.3"

[[packages]]
name = "japanese-usage-dictionary"
sha256sum = "140f24f71f7d78d5eb5b93a9c079f44f23728dca5ab16bf857fe8a3fa1bf20ed"
downloadLocation = "https://github.com/hiroyuki-komatsu/japanese-usage-dictionary/archive/refs/tags/2025-01-25.zip"
license = "SUSE-Public-Domain"
version = "2025-01-25"

[[packages]]
name = "bazelbuild/rules_java"
sha256sum = "c5bc17e17bb62290b1fd8fdd847a2396d3459f337a7e07da7769b869b488ec26"
downloadLocation = "https://github.com/bazelbuild/rules_java/releases/download/8.6.1/rules_java-8.6.1.tar.gz"
license = "Apache-2.0"
version = "8.6.1"

[[packages]]
name = "bazelbuild/rules_kotlin"
sha256sum = "3b772976fec7bdcda1d84b9d39b176589424c047eb2175bed09aac630e50af43"
downloadLocation = "https://github.com/bazelbuild/rules_kotlin/releases/download/v1.9.6/rules_kotlin-v1.9.6.tar.gz"
license = "Apache-2.0"
version = "1.9.6"

[[packages]]
name = "bazelbuild/rules_shell"
sha256sum = "410e8ff32e018b9efd2743507e7595c26e2628567c42224411ff533b57d27c28"
downloadLocation = "https://github.com/bazelbuild/rules_shell/releases/download/v0.2.0/rules_shell-v0.2.0.tar.gz"
license = "Apache-2.0"
version = "0.2.0"

[[packages]]
name = "bazelbuild/rules_python"
sha256sum = "4f7e2aa1eb9aa722d96498f5ef514f426c1f55161c3c9ae628c857a7128ceb07"
downloadLocation = "https://github.com/bazelbuild/rules_python/releases/download/1.0.0/rules_python-1.0.0.tar.gz"
license = "Apache-2.0"
version = "1.0.0"

[[packages]]
name = "bazelbuild/rules_cc"
sha256sum = "abc605dd850f813bb37004b77db20106a19311a96b2da1c92b789da529d28fe1"
downloadLocation = "https://github.com/bazelbuild/rules_cc/releases/download/0.0.17/rules_cc-0.0.17.tar.gz"
license = "Apache-2.0"
version = "0.0.17"

[[packages]]
name = "bazelbuild/bazel-skylib"
sha256sum = "bc283cdfcd526a52c3201279cda4bc298652efa898b10b4db0837dc51652756f"
downloadLocation = "https://github.com/bazelbuild/bazel-skylib/releases/download/1.7.1/bazel-skylib-1.7.1.tar.gz"
license = "Apache-2.0"
version = "1.7.1"

[[packages]]
name = "protobuf"
sha256sum = "e9b9ac1910b1041065839850603caf36e29d3d3d230ddf52bd13778dd31b9046"
downloadLocation = "https://github.com/protocolbuffers/protobuf/releases/download/v29.3/protobuf-29.3.zip"
license = "BSD-3-Clause AND MIT"
version = "29.3"

[[packages]]
# Not extracted into bazel-src/external.
name = "bazel-contrib/bazel_features"
sha256sum = "af3d4fb1cf4f25942cb4a933b1ad93a0ea9fe9ee70c2af7f369fb72a67c266e5"
downloadLocation = "https://github.com/bazel-contrib/bazel_features/releases/download/v1.21.0/bazel_features-v1.21.0.tar.gz"
license = "Apache-2.0"
version = "1.21.0"

[[packages]]
# Not extracted into bazel-src/external.
name = "bazelbuild/rules_apple"
sha256sum = "352428421c89dba8859055c3e1ba42f742c224544bf0e196c926d1cf44a2d726"
downloadLocation = "https://github.com/bazelbuild/rules_apple/releases/download/3.16.1/rules_apple.3.16.1.tar.gz"
license = "Apache-2.0"
version = "3.16.1"

[[packages]]
# Not extracted into bazel-src/external.
name = "bazelbuild/rules_swift"
sha256sum = "9919ed1d8dae509645bfd380537ae6501528d8de971caebed6d5185b9970dc4d"
downloadLocation = "https://github.com/bazelbuild/rules_swift/releases/download/2.1.1/rules_swift.2.1.1.tar.gz"
license = "Apache-2.0"
version = "2.1.1"

[[packages]]
# Not extracted into bazel-src/external.
name = "apple_support.1.16.0.tar.gz"
sha256sum = "c31ce8e531b50ef1338392ee29dd3db3689668701ec3237b9c61e26a1937ab07"
downloadLocation = "https://github.com/bazelbuild/apple_support/releases/download/1.16.0/apple_support.1.16.0.tar.gz"
license = "Apache-2.0"
version = "1.16.0"

[[packages]]
name = "platforms-0.0.10.tar.gz"
sha256sum = "218efe8ee736d26a3572663b374a253c012b716d8af0c07e842e82f238a0a7ee"
downloadLocation = "https://github.com/bazelbuild/platforms/releases/download/0.0.10/platforms-0.0.10.tar.gz"
license = "Apache-2.0"
version = "0.0.10"

[[packages]]
name = "bazelbuild/rules_pkg"
sha256sum = "d20c951960ed77cb7b341c2a59488534e494d5ad1d30c4818c736d57772a9fef"
downloadLocation = "https://github.com/bazelbuild/rules_pkg/releases/download/1.0.1/rules_pkg-1.0.1.tar.gz"
license = "Apache-2.0"
version = "1.0.1"

[[packages]]
name = "bazelbuild/rules_license"
sha256sum = "26d4021f6898e23b82ef953078389dd49ac2b5618ac564ade4ef87cced147b38"
downloadLocation = "https://github.com/bazelbuild/rules_license/releases/download/1.0.0/rules_license-1.0.0.tar.gz"
license = "Apache-2.0"
version = "1.0.0"

[[packages]]
name = "abseil-cpp"
sha256sum = "16242f394245627e508ec6bb296b433c90f8d914f73b9c026fddb905e27276e8"
downloadLocation = "https://github.com/abseil/abseil-cpp/releases/download/20250127.0/abseil-cpp-20250127.0.tar.gz"
license = "Apache-2.0"
version = "20250127.0"

[[packages]]
name = "zlib"
sha256sum = "9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23"
downloadLocation = "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz"
license = "Zlib"
version = "1.3.1"

[[packages]]
# material_icon_dictionary_svg
name = "google/material-design-icons/action/chrome_reader_mode"
sha256sum = "a4c7b9bfb442a7497b72d74358c31034c4fef1ab2a50659834784580751ac04d"
downloadLocation = "https://raw.githubusercontent.com/google/material-design-icons/4.0.0/src/action/chrome_reader_mode/materialiconsoutlined/24px.svg"
license = "Apache-2.0"
version = "4.0.0"

[[packages]]
# material_icon_tool_svg
name = "google/material-design-icons/action/build"
sha256sum = "df34fba3d09778db69503a23b688761051dbf65b5bccb0d7b729c69ff61c3804"
downloadLocation = "https://raw.githubusercontent.com/google/material-design-icons/4.0.0/src/action/build/materialicons/24px.svg"
license = "Apache-2.0"
version = "4.0.0"

[[packages]]
# material_icon_dictionary_png
name = "google/material-design-icons/action/chrome_reader_mode"
sha256sum = "6d2ac7befa038d4f32e07136293acaf5d8645a4daecb6d063f34be2ffea59b55"
downloadLocation = "https://raw.githubusercontent.com/google/material-design-icons/4.0.0/png/action/chrome_reader_mode/materialiconsoutlined/48dp/1x/outline_chrome_reader_mode_black_48dp.png"
license = "Apache-2.0"
version = "4.0.0"

[[packages]]
# material_icon_properties_svg
name = "google/material-design-icons/action/settings"
sha256sum = "9b01b133be1caffc680f132d385d0e594262d6cfd29759a63c428050b83fe628"
downloadLocation = "https://raw.githubusercontent.com/google/material-design-icons/4.0.0/src/action/settings/materialiconsround/24px.svg"
license = "Apache-2.0"
version = "4.0.0"

[[packages]]
# material_icon_properties_png
name = "google/material-design-icons/action/settings"
sha256sum = "c4ae8bb7992f43157be9d026f76a7039af6e0e3de0f220842208dfda8c38714a"
downloadLocation = "https://raw.githubusercontent.com/google/material-design-icons/4.0.0/png/action/settings/materialiconsround/48dp/1x/round_settings_black_48dp.png"
license = "Apache-2.0"
version = "4.0.0"

[[packages]]
# material_icon_tool_png
name = "google/material-design-icons/action/build"
sha256sum = "269433bf6d6948a93ab6a57a73ceb5930870223046052cfffe01eeca37327d3e"
downloadLocation = "https://raw.githubusercontent.com/google/material-design-icons/4.0.0/png/action/build/materialicons/48dp/1x/baseline_build_black_48dp.png"
license = "Apache-2.0"
version = "4.0.0"

[[packages]]
name = "hiroyuki-komatsu/japanpost_zipcode/zip_code_jigyosyo"
sha256sum = "1c56e79ff4c7f709778e0bf4dfbffdf939efd170845feccae986d22cf4373988"
downloadLocation = "https://github.com/hiroyuki-komatsu/japanpost_zipcode/raw/6ece210081fb73d0ea4a5ea8e13ac9584d03fd76/jigyosyo.zip"
license = "SUSE-Public-Domain"
version = "2025-03-08"

[[packages]]
name = "hiroyuki-komatsu/japanpost_zipcode/zip_code_kenall"
sha256sum = "296cfa57f2012c0226afbc64e9e8575fc36285d2fa31d725a176548cd173b3df"
downloadLocation = "https://github.com/hiroyuki-komatsu/japanpost_zipcode/raw/6ece210081fb73d0ea4a5ea8e13ac9584d03fd76/ken_all.zip"
license = "SUSE-Public-Domain"
version = "2025-03-08"